import {
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Bot,
  Calendar,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CircleX,
  Clock3,
  File,
  FileText,
  FolderOpen,
  GraduationCap,
  Home,
  LayoutDashboard,
  LoaderCircle,
  LogOut,
  MessageSquare,
  Plus,
  School,
  Send,
  Settings,
  Sparkles,
  Upload,
  User,
  type LucideIcon,
} from "lucide-react";

export type AppIcon = LucideIcon;

export const AppIcons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  back: ChevronLeft,
  forward: ChevronRight,
  dashboard: LayoutDashboard,
  home: Home,
  classes: School,
  classFolder: FolderOpen,
  settings: Settings,
  help: CircleHelp,
  logout: LogOut,
  upload: Upload,
  file: File,
  fileText: FileText,
  chat: MessageSquare,
  quiz: CheckCircle2,
  flashcards: BookOpen,
  bot: Bot,
  calendar: Calendar,
  clock: Clock3,
  send: Send,
  add: Plus,
  check: Check,
  success: CheckCircle2,
  error: CircleX,
  loading: LoaderCircle,
  user: User,
  sparkles: Sparkles,
  graduation: GraduationCap,
} as const;
